# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

STenrich_permutation_helper <- function(coords, n_subsample, n_samples) {
    .Call(`_spatialGE_STenrich_permutation_helper`, coords, n_subsample, n_samples)
}

STenrich_permutation_fast <- function(coords, n_subsample, n_samples) {
    .Call(`_spatialGE_STenrich_permutation_fast`, coords, n_subsample, n_samples)
}

STenrich_permutation_fast <- function(coords, n_subsample, n_samples) {
    .Call(`_spatialGE_STenrich_permutation_fast`, coords, n_subsample, n_samples)
}

STenrich_pvalue_calculation <- function(null_distribution, observed_distance, n_samples) {
    .Call(`_spatialGE_STenrich_pvalue_calculation`, null_distribution, observed_distance, n_samples)
}

SparseRowVar2 <- function(mat, mu) {
    .Call(`_spatialGE_SparseRowVar2`, mat, mu)
}

SparseRowVarStd <- function(mat, mu, sd, vmax) {
    .Call(`_spatialGE_SparseRowVarStd`, mat, mu, sd, vmax)
}

computeSubsampleSums <- function(coords, n_subsample, n_samples) {
    .Call(`_spatialGE_computeSubsampleSums`, coords, n_subsample, n_samples)
}

